backend_user:
    resource: "@BackendBundle/Controller/UserController.php"
    type:     annotation

backend_command:
    resource: "@BackendBundle/Controller/CommandController.php"
    type:     annotation

backend_client:
    resource: "@BackendBundle/Controller/ClientController.php"
    type:     annotation

backend_article:
    resource: "@BackendBundle/Controller/ArticleController.php"
    type:     annotation

frontend:
    resource: "@FrontendBundle/Controller/"
    type:     annotation
    prefix:   /

backend:
    resource: "@BackendBundle/Controller/"
    type:     annotation
    prefix:   /admin

app:
    resource: '@AppBundle/Controller/'
    type: annotation
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"