<?php

namespace BackendBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
	public function pagination($filter)
	{
        $query = $this->createQueryBuilder('a')
            ->select('a')
            ->where ('a.active = 1')
            ->orderby($filter);
            //->addOrderBy($filter);
    
    return $query;

	}

    public function paginationNotActive($filter)
    {
        $query = $this->createQueryBuilder('a')
            ->select('a')
            ->orderby($filter);
        //->addOrderBy($filter);

        return $query;

    }

    public function findArray($array)
    {
        $qb = $this->createQueryBuilder('a')
            ->select('a') 
            ->where ('a.id IN (:array)')
            ->setParameter('array', $array);

        return $qb->getQuery()->getResult(); 
    }
}