<?php

namespace BackendBundle\Repository;

/**
 * CommandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandRepository extends \Doctrine\ORM\EntityRepository
{
    public function findLast()
    {
        $qb = $this->createQueryBuilder('c');
        $qb->setMaxResults( 1 );
        $qb->orderBy('c.id', 'DESC');

        return $qb->getQuery()->getSingleResult();
    }

    public function pagination($filter)
    {
        $query = $this->createQueryBuilder('c')
            ->select('c')
            ->orderBy($filter);

        return $query;
    }

    public function paginationClient()
    {
        $query = $this->createQueryBuilder('c')
            ->select('DISTINCT c.lastname, c.firstname, c.email, c.totalCommand, c.dateCommand');

        return $query;
    }

}
