<?php

namespace BackendBundle\Repository;

/**
 * CommandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandRepository extends \Doctrine\ORM\EntityRepository
{
    public function findLast()
    {
        $qb = $this->createQueryBuilder('c');
        $qb->setMaxResults( 1 );
        $qb->orderBy('c.id', 'DESC');

        return $qb->getQuery()->getSingleResult();
    }
}
